/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/4q5c0CAtkzb
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

export function Home() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-gray-900 py-4 md:py-6">
        <div className="container px-4 md:px-6 flex items-center justify-between">
          <div className="flex items-center">
            <Link className="text-white font-bold text-lg" href="#">
              Movie App
            </Link>
          </div>
          <div className="flex items-center space-x-4">
            <Link className="text-gray-400 hover:text-white transition-colors" href="#">
              Sign Up
            </Link>
            <Button className="bg-primary text-white px-6 py-3 rounded-md hover:bg-primary/80 focus:ring-2 focus:ring-primary focus:outline-none">
              Login
            </Button>
          </div>
          <div className="flex items-center space-x-4">
            <Link className="text-gray-400 hover:text-white transition-colors" href="#">
              Profile
            </Link>
            <Button className="bg-gray-800 text-white px-6 py-3 rounded-md hover:bg-gray-700 focus:ring-2 focus:ring-gray-800 focus:outline-none">
              Logout
            </Button>
          </div>
        </div>
      </header>
      <section className="bg-gray-900 py-20 md:py-32">
        <div className="container px-4 md:px-6">
          <div className="max-w-3xl mx-auto text-center space-y-6">
            <h1 className="text-3xl font-bold text-white sm:text-4xl md:text-5xl">Discover the Best Movies</h1>
            <p className="text-gray-400 text-lg">Search for movies, read reviews, and share your thoughts.</p>
            <form className="flex items-center max-w-xl mx-auto">
              <Input
                className="flex-1 bg-gray-800 border-none text-white placeholder-gray-400 focus:ring-2 focus:ring-primary focus:outline-none"
                placeholder="Search for a movie..."
                type="text"
              />
              <Button
                className="bg-primary text-white px-6 py-3 rounded-md ml-4 hover:bg-primary/80 focus:ring-2 focus:ring-primary focus:outline-none"
                type="submit"
              >
                Search
              </Button>
            </form>
          </div>
        </div>
      </section>
      <section className="py-12 md:py-20">
        <div className="container px-4 md:px-6">
          <div className="mb-8 md:mb-12">
            <h2 className="text-2xl font-bold mb-2">Latest Movies</h2>
            <p className="text-gray-500">Check out the latest movie releases.</p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6" />
        </div>
      </section>
      <section className="bg-gray-100 py-12 md:py-20">
        <div className="container px-4 md:px-6">
          <div className="mb-8 md:mb-12">
            <h2 className="text-2xl font-bold mb-2">Movie Reviews</h2>
            <p className="text-gray-500">Read reviews from other users and share your own thoughts.</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6" />
          <div className="mt-8 md:mt-12 text-center">
            <Button className="bg-primary text-white px-6 py-3 rounded-md hover:bg-primary/80 focus:ring-2 focus:ring-primary focus:outline-none">
              Write a Review
            </Button>
          </div>
        </div>
      </section>
    </div>
  )
}
